openapi: 3.0.0
info:
  title: Error Report API
  description: API for reporting errors from client applications
  version: 1.0.0
servers:
  - url: http://127.0.0.1:8080
    description: Local development server
paths:
  /api/v1/error-report:
    post:
      summary: Report an error
      description: Send an error report from a client application to be propagated to Telegram
      operationId: reportError
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ErrorReportRequest'
      responses:
        '200':
          description: Error report received and processed
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Error report received and processed
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: Unprocessable entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - ApiKeyAuth: []
components:
  schemas:
    ErrorReportRequest:
      type: object
      required:
        - app
        - device
        - error
      properties:
        app:
          $ref: '#/components/schemas/App'
        device:
          $ref: '#/components/schemas/Device'
        error:
          $ref: '#/components/schemas/Error'
    App:
      type: object
      required:
        - name
        - version
      properties:
        name:
          type: string
          minLength: 1
        version:
          type: string
          minLength: 1
    Device:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          minLength: 1
        description:
          type: string
    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          minLength: 1
        trace:
          type: array
          items:
            type: string
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        message:
          type: string
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
      description: API key in the format "Bearer {api_key}"